#!/bin/sh

curr_dir=$(cd `dirname $0`; pwd)
old_gopath=$GOPATH
export GOPATH=$curr_dir

src_dir="src"
if [ ! -d ${src_dir}"/github.com/astaxie/beego" ]; then
    go get "github.com/astaxie/beego"
fi

if [ ! -d ${src_dir}"/github.com/beego/bee" ]; then
    go get "github.com/beego/bee"
fi

if [ ! -d ${src_dir}"/github.com/garyburd/redigo" ]; then
    go get github.com/garyburd/redigo/redis
fi

if [ ! -d ${src_dir}"/github.com/go-yaml/yaml" ]; then
    go get github.com/go-yaml/yaml
fi

if [ ! -d ${src_dir}"/github.com/mattn/go-sqlite3" ]; then
    go get github.com/mattn/go-sqlite3
fi

export GOPATH=$old_gopath
