#!同级的字段缩进相同，且只能用空格缩进
#!每个字段value值前相对“-”或者“：”必须有空格

#[redis服务相关配置]

#redis服务器
servers:
 - server: 127.0.0.1
   port: 6379
   conntype: tcp
# - server: 127.0.0.1
#   port: 6479
#   conntype: tcp

#获取redis信息间隔时间(秒)
sleeptime: 30

#redis连接池最大连接数
maxidle: 3

#redis连接池最大活跃数,0表示无限制
maxactive: 3

#redis连接池连接超时时间,0表示不超时
idletimeout: 0

#存储数据类型
datatype: sqlite
#数据存储路径
datapath: ./data/redisfox.db

#日志相关
logpath: ./log/
logname: redisfox
loglevel: DEBUG
logexpire: 7

#web访问ip
serverip: 127.0.0.1
#web访问端口
serverport: 8080
#web调试模式是否开启
debugmode: 0

#静态文件目录
staticdir: ./static/
#模板文件目录
tpldir: ./tpl/